[program:cricos]
command=/home/cricos/venv/bin/uwsgi
 --chdir /home/cricos
 -w main.wsgi:application
 --http-socket=/home/cricos/uwsgi_panel.sock
 --stats=/home/cricos/uwsgi_panel_stats.sock
 --umask=000
 --env DJANGO_SETTINGS_MODULE=main.settings_production
 --touch-reload=main/wsgi.py
 --enable-threads
 -H /home/cricos/venv
 --processes=2
 --max-requests=100
 --harakiri=60
 --lazy-apps
 --auto-procname
 --procname-prefix=%(program_name)s-
 --req-logger=file:/var/log/uwsgi/%(program_name)s.log
 --log-format='{"unix": %%(time), "time": "%%(ltime)", "ip": "%%(var.HTTP_X_FORWARDED_FOR)", "host": "%%(host)", "path": "%%(var.PATH_INFO)", "query": "%%(var.QUERY_STRING)", "method": "%%(method)", "status": %%(status), "size": %%(size), "ua": "%%(uagent)", "ref": "%%(referer)", "us": %%(micros)}'
directory=/home/cricos
environment=PYTHONUNBUFFERED=1,PATH="/home/cricos/venv/bin:%(ENV_PATH)s"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=cricos
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
startretries=1000000000

[program:indexnow]
command=/home/cricos/venv/bin/python manage.py indexnow --domain cricos.net --key 3bbfb19b0bff407ebd17ba1ef3aa314b -v 3
directory=/home/cricos
environment=PYTHONUNBUFFERED=1,PATH="/home/cricos/venv/bin:%(ENV_PATH)s"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=cricos
redirect_stderr=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
startretries=1000000000
