"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-lzi@1-r54=400vw&_^7jg&s7xm-w)zdulsda(vl%onxbjhyxtn"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "debug_toolbar",
    "cricos",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "metasite.tools.middleware.SitesMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cricos.context_processors.menu",
                "cricos.context_processors.template_settings",
                "metasite.tools.context_processors.site",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

METASITE_TOKEN = '65fed24f-db58-45ab-bc27-a9dc64826d65'
METASITE_BACKEND = 'http://127.0.0.1:8019'

SITEMAPS_SOURCES = [
    ('cricos.sitemap', 'BlogSitemap'),
]

SITEMAPS_ROOT = os.path.join(BASE_DIR, 'sitemaps_cache')

MAX_PAGE_SIZE = 50

POPULAR_CITY_NAMES = (
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Hobart",
    "Darwin",
    "Newcastle",
    "Wollongong",
    "Cairns",
)

POPULAR_STUDY_AREAS = (
    {"name": "Business", "keywords": ("business",)},
    {"name": "Nursing", "keywords": ("nursing",)},
    {"name": "Information Technology", "keywords": ("information technology",)},
    {"name": "Engineering", "keywords": ("engineering",)},
    {"name": "English", "keywords": ("english",)},
    {"name": "Community Services", "keywords": ("community services",)},
    {"name": "Hospitality", "keywords": ("hospitality",)},
    {"name": "Early Childhood Education", "keywords": ("early childhood",)},
)

POPULAR_STATES = (
    {"name": "New South Wales", "code": "NSW"},
    {"name": "Victoria", "code": "VIC"},
    {"name": "Queensland", "code": "QLD"},
    {"name": "Western Australia", "code": "WA"},
    {"name": "South Australia", "code": "SA"},
    {"name": "Australian Capital Territory", "code": "ACT"},
    {"name": "Tasmania", "code": "TAS"},
    {"name": "Northern Territory", "code": "NT"},
)

POPULAR_COMBINATIONS = (
    {"label": "English courses in Sydney", "city": "Sydney", "q": "English"},
    {"label": "Nursing courses in Melbourne", "city": "Melbourne", "q": "Nursing"},
    {"label": "Business courses in Brisbane", "city": "Brisbane", "q": "Business"},
    {"label": "IT courses in Perth", "city": "Perth", "q": "Information Technology"},
    {"label": "Engineering courses in Adelaide", "city": "Adelaide", "q": "Engineering"},
)

INTERNAL_IPS = [
    "127.0.0.1",
]

REDIS = {
    'host': 'localhost',
    'port': 6379,
    'db': 6,
}

REDIS_INDEXNOW = 'cricos_indexnow'
