# Generated by Django 6.0.3 on 2026-03-11 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_name", models.CharField(max_length=512)),
                ("source_file_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "dataset_datetime",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_current", models.BooleanField(default=False)),
                ("institutions_count", models.PositiveIntegerField(default=0)),
                ("courses_count", models.PositiveIntegerField(default=0)),
                ("locations_count", models.PositiveIntegerField(default=0)),
                ("course_locations_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("content_type", models.CharField(max_length=100)),
                ("content", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "publish_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("seo_description", models.CharField(max_length=180, null=True)),
                ("seo_title", models.CharField(max_length=100, null=True)),
                ("seo_keyphrase", models.CharField(max_length=100, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_code", models.CharField(db_index=True, max_length=32)),
                (
                    "institution_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("active_courses_count", models.PositiveIntegerField(default=0)),
                ("total_courses_count", models.PositiveIntegerField(default=0)),
                ("campuses_count", models.PositiveIntegerField(default=0)),
                ("cities_count", models.PositiveIntegerField(default=0)),
                ("states_count", models.PositiveIntegerField(default=0)),
                ("trading_name", models.CharField(blank=True, max_length=255)),
                ("institution_type", models.CharField(blank=True, max_length=255)),
                (
                    "institution_capacity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("website", models.CharField(blank=True, max_length=500)),
                ("postal_address_line_1", models.CharField(blank=True, max_length=255)),
                ("postal_address_line_2", models.CharField(blank=True, max_length=255)),
                ("postal_address_line_3", models.CharField(blank=True, max_length=255)),
                ("postal_address_line_4", models.CharField(blank=True, max_length=255)),
                ("postal_city", models.CharField(blank=True, max_length=255)),
                ("postal_state", models.CharField(blank=True, max_length=255)),
                ("postal_postcode", models.CharField(blank=True, max_length=64)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cricos.dataset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_code", models.CharField(db_index=True, max_length=32)),
                ("course_code", models.CharField(db_index=True, max_length=64)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                (
                    "course_name",
                    models.CharField(blank=True, db_index=True, max_length=500),
                ),
                ("search_text", models.TextField(blank=True)),
                (
                    "popular_study_area",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("campuses_count", models.PositiveIntegerField(default=0)),
                ("vet_national_code", models.CharField(blank=True, max_length=128)),
                ("dual_qualification", models.CharField(blank=True, max_length=255)),
                ("course_level", models.CharField(blank=True, max_length=255)),
                ("foundation_studies", models.CharField(blank=True, max_length=255)),
                ("work_component", models.CharField(blank=True, max_length=255)),
                (
                    "work_component_hours_per_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("work_component_weeks", models.IntegerField(blank=True, null=True)),
                (
                    "work_component_total_hours",
                    models.IntegerField(blank=True, null=True),
                ),
                ("course_language", models.CharField(blank=True, max_length=255)),
                (
                    "duration_weeks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "non_tuition_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estimated_total_course_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("field_1_broad", models.CharField(blank=True, max_length=255)),
                ("field_1_narrow", models.CharField(blank=True, max_length=255)),
                ("field_1_detailed", models.CharField(blank=True, max_length=255)),
                ("field_2_broad", models.CharField(blank=True, max_length=255)),
                ("field_2_narrow", models.CharField(blank=True, max_length=255)),
                ("field_2_detailed", models.CharField(blank=True, max_length=255)),
                ("expired", models.BooleanField(default=False)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cricos.dataset"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cricos.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_code", models.CharField(db_index=True, max_length=32)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                (
                    "location_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("location_type", models.CharField(blank=True, max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("address_line_4", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, db_index=True, max_length=255)),
                ("state", models.CharField(blank=True, db_index=True, max_length=255)),
                ("postcode", models.CharField(blank=True, max_length=64)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cricos.dataset"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cricos.institution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("module", models.CharField(db_index=True, max_length=40)),
                ("submodule", models.CharField(db_index=True, max_length=100)),
                ("message", models.CharField(max_length=1000)),
                ("data", models.TextField(blank=True, default=None, null=True)),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CourseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_code", models.CharField(db_index=True, max_length=32)),
                ("course_code", models.CharField(db_index=True, max_length=64)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "location_city",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "location_state",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cricos.course",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cricos.dataset"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cricos.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dataset", "location_city", "course"],
                        name="cricos_cl_ds_city_course",
                    ),
                    models.Index(
                        fields=["dataset", "location_state", "course"],
                        name="cricos_cl_ds_state_course",
                    ),
                ],
            },
        ),
    ]
